<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * English language strings for block_reports_custom.
 *
 * @package    block_reports_custom
 * @copyright  2025 Alonso Arias <soporte@ingeweb.co>
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

// Plugin name.
$string['pluginname'] = 'Custom Reports Block';
$string['reports_custom'] = 'Custom Reports';

// Report Titles.
$string['certificates_report'] = 'Certificates Generated by Courses';
$string['progress_report'] = 'Courses - User Progress Detail - Grade and Date';

// Capabilities.
$string['reports_custom:addinstance'] = 'Add a new Custom Reports block';
$string['reports_custom:myaddinstance'] = 'Add a new Custom Reports block to Dashboard';
$string['reports_custom:view'] = 'View the Custom Reports block';
$string['reports_custom:viewreports'] = 'View custom reports';

// Table Headers.
$string['header_cedula'] = 'ID Number';
$string['header_nombres'] = 'First Name';
$string['header_apellidos'] = 'Last Name';
$string['header_clinica'] = 'Clinic';
$string['header_area'] = 'Area';
$string['header_nombrecurso'] = 'Course Name';
$string['header_fecha'] = 'Date';
$string['header_categoriacurso'] = 'Course Category';
$string['header_user_type'] = 'User Type';
$string['header_usuario'] = 'Username';
$string['header_nombre'] = 'Name';
$string['header_apellido'] = 'Surname';
$string['header_nombre_completo'] = 'Full Name';
$string['header_categoria'] = 'Category';
$string['header_curso'] = 'Course';
$string['header_item'] = 'Item';
$string['header_calificacion'] = 'Grade';

// Form Options.
$string['option_todos'] = 'All';
$string['option_category'] = 'Category';
$string['option_course'] = 'Course';
$string['option_usertype'] = 'User Type';
$string['option_nombre'] = 'First Name';
$string['option_apellido'] = 'Last Name(s)';
$string['option_download_format'] = 'Download Format';
$string['option_download_excel'] = 'Excel';
$string['option_download_ods'] = 'ODS';
$string['option_download_csv'] = 'CSV';

// Other.
$string['report_title'] = 'Report';
$string['report_heading'] = 'Report';
$string['btn_descargar'] = 'Download';
$string['alphabet_all'] = 'All';
$string['total_records'] = 'Total Records';
$string['idnumber'] = 'ID Number';
$string['start_date'] = 'Start Date';
$string['end_date'] = 'End Date';
$string['records_per_page'] = 'Records per page';
$string['show_records'] = 'Show';

// Settings.
$string['settings_restrictions_heading'] = 'Role-Category Restrictions';
$string['settings_restrictions_desc'] = 'Configure which roles are restricted to view only certain course categories in reports.';
$string['settings_role_category_mappings'] = 'Role to Category Mappings';
$string['settings_role_category_mappings_desc'] = 'Enter one mapping per line in the format: role_id:category_id1,category_id2<br>Example:<br>11:72,73<br>12:74<br><br>Users with these roles will only see data from the specified categories. Users without any of these roles will have no restrictions.';
$string['settings_reports_heading'] = 'Report Settings';
$string['settings_reports_desc'] = 'Configure general report settings.';
$string['settings_records_per_page'] = 'Records per page';
$string['settings_records_per_page_desc'] = 'Number of records to display per page in reports.';
$string['settings_user_type_field'] = 'User type field';
$string['settings_user_type_field_desc'] = 'The shortname of the user profile field that contains the user type.';
$string['settings_unassigned_label'] = 'Unassigned label';
$string['settings_unassigned_label_desc'] = 'Label to display when a user has no user type assigned.';

// Errors.
$string['customcert_not_installed'] = 'The Custom Certificate plugin is required but not installed.';

// Privacy.
$string['privacy:metadata'] = 'The Custom Reports block does not store any personal data. It only displays data from other Moodle components.';
