<?php

// Plugin name
$string['pluginname'] = 'Reports Custom Block';
$string['reports_custom'] = 'Reports Custom';

// Report Titles
$string['certificates_report'] = 'Certificates Generated by Courses';
$string['progress_report'] = 'Courses - User Progress Detail - Grade and Date';

// Capabilities
$string['reports_custom:addinstance'] = 'Add a new Reports Custom block';
$string['reports_custom:myaddinstance'] = 'Add a new Reports Custom block to the My Moodle page';

// Table Headers
$string['header_cedula'] = 'ID';
$string['header_nombres'] = 'First Name';
$string['header_apellidos'] = 'Last Name';
$string['header_clinica'] = 'Clinic';
$string['header_area'] = 'Area';
$string['header_nombrecurso'] = 'Course Name';
$string['header_fecha'] = 'Date';
$string['header_categoriacurso'] = 'Course Category';
$string['header_user_type'] = 'User Type';
$string['header_usuario'] = 'Username';
$string['header_nombre'] = 'Name';
$string['header_apellido'] = 'Surname';
$string['header_nombre_completo'] = 'Full Name';
$string['header_categoria'] = 'Category';
$string['header_curso'] = 'Course';
$string['header_item'] = 'Item';
$string['header_calificacion'] = 'Grade';

// Form Options
$string['option_todos'] = 'All';
$string['option_category'] = 'Category';
$string['option_course'] = 'Course';
$string['option_usertype'] = 'User Type';
$string['option_nombre'] = 'First Name';
$string['option_apellido'] = 'Last Name(s)';
$string['option_download_format'] = 'Download Format';
$string['option_download_excel'] = 'Excel';
$string['option_download_ods'] = 'ODS';
$string['option_download_csv'] = 'CSV';

// Other
$string['report_title'] = 'Report';
$string['report_heading'] = 'Report';
$string['btn_descargar'] = 'Download';
$string['alphabet_all'] = 'All';
$string['total_records'] = 'Total Records';


?>
